### ISSUE TITLE
Fix TravisCI link

### ISSUE THREAD

**Issue by Trost123** [contra/gulp-beautify#21]
Currently it points to https://travis-ci.org/wearefractal/gulp-beautify, which results in no image.
(In https://www.npmjs.com/package/gulp-beautify and in https://github.com/contra/gulp-beautify)

**Comment by contra** [comment]
PR?

**Comment by Trost123** [comment]
#22 
Not sure how to PR a change here:
https://www.npmjs.com/package/gulp-beautify

**Comment by contra** [comment]
Thanks
