### ISSUE TITLE
Should prefer breaking the line after operator ? instead of before operator <

### ISSUE THREAD

**Issue by knocte** [contra/gulp-beautify#23]
I found an issue with the beautifier, it tries to change this kind of code:

```
<td>{{(transaction.amount < 0 ? 'withdrawal' : 'deposit') | translate}}</td>
```

To this:

```
<td>{{(transaction.amount
    < 0 ? 'withdrawal' : 'deposit') | translate}}</td>
```

It does it because I've configured it with a certain column limit, and that's alright.

But the way it breaks the line makes it super ugly.

Ideally, it should try to break the line this way:

```
<td>{{(transaction.amount < 0 ?
        'withdrawal' : 'deposit') | translate}}</td>
```

**Comment by contra** [comment]
This is just a gulp wrapper on top of https://github.com/beautify-web/js-beautify - open your issue with them.
